pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    environment {
        REPO_URL = 'https://github.com/EverestPhone/grpc.git'
        DOXYGEN_CONFIG = 'Doxyfile'
        OUTPUT_ARCHIVE = 'doc.tar.gz'
    }

    stages {

        stage('Checkout RepoA') {
            steps {
                git branch: 'main', url: "${env.REPO_URL}"
            }
        }

        stage('Generate Doxygen Config') {
            steps {
                bat "doxygen -g %DOXYGEN_CONFIG%"
            }
        }

        stage('Run Doxygen') {
            steps {
                bat "doxygen %DOXYGEN_CONFIG%"
            }
        }

        stage('Pack Documentation') {
            steps {
                bat """
                if exist html (
                    tar -czf %OUTPUT_ARCHIVE% html
                ) else (
                    echo ERROR: html folder not found
                    exit /b 1
                )
                """
            }
        }

        stage('Archive Artifact') {
            steps {
                archiveArtifacts artifacts: "${OUTPUT_ARCHIVE}"
            }
        }
    }
}
